BurntSushi/byteorder

README.md, src/lib.rs
Updated all uses of std::old_io to std::io including removing the unused `lg!` macro.
Resolves #2
=> Updated to new std::io

src/lib.rs
Warning: tests fail due to changes needed in quickcheck (the same as the newio PR)
=> Update master for nightly changes

src/lib.rs
Even though this looks like a compiler issue with optimisations, I hereby propose the patch mentioned in rust-lang/rust#22776 as an unintrusive (temporary) workaround, since cross-compiling `byteorder` to Android ARM with optimisations is broken otherwise and the issue can be difficult to diagnose.
=> Unintrusive workaround for rust-lang/rust#22776.

src/new.rs
This is what Read::read_to_end does. You might also want to consider re-trying/returning partial results on resource unavailable errors but that's debatable.
=> Retry on interrupt.

src/lib.rs
The term "task failure" is obsolete (see [RFC 221](https://github.com/rust-lang/rfcs/blob/master/text/0221-panic.md]) / rust-lang/rust#17489). Update the docs to match.
=> Change "Task failure occurs when" to "Panics when"

src/lib.rs, src/new.rs
Without `#[inline]`, the function definition is not exported for inlining by other crates. For the byte order conversion functions, inlining can make a great difference in code quality.
For example, trying this small test crate:
extern crate byteorder;
use byteorder::{ByteOrder, LittleEndian};
pub fn example(buf: &[u8; 8]) -> u64 {
LittleEndian::read_u64(buf)
}
The result without `#[inline]` in the `byteorder` crate:
_ZN7example20h618e367dcb99bd17iaaE:
.cfi_startproc
cmpq    %fs:112, %rsp
ja      .LBB0_2
movabsq $24, %r10
movabsq $0, %r11
callq   __morestack
retq
.LBB0_2:
subq    $24, %rsp
.Ltmp0:
.cfi_def_cfa_offset 32
movq    %rdi, 8(%rsp)
movq    $8, 16(%rsp)
leaq    8(%rsp), %rdi
callq   _ZN22LittleEndian.ByteOrder8read_u6420hc703c516084f60e83EaE@PLT
addq    $24, %rsp
retq
The result …
=> Add #[inline] to allow for cross-crate inlining

Cargo.toml, src/lib.rs
It is behind feature so it won't affect current users, but allow others to remove dependency when not needed.
=> Allow builds without std dependency

src/lib.rs, src/new.rs
Now that 1.6 is released, all of this functionality is stable in the standard library.
=> Remove custom error type

src/lib.rs
Network byte order is defined by [RFC 1700][1] to be big-endian, and is
referred to in several protocol specifications.  This type is an alias
of BigEndian.  This alias can be used to make it more clear why you're
using a particular byte order in code, if you are implementing a
specification that refers to network byte order.
[1]: https://tools.ietf.org/html/rfc1700
=> Add NetworkEndian alias

Cargo.toml, README.md, src/lib.rs
Please also publish the new version to crates.io :)
=> Enable usage in no_std contexts

src/lib.rs
Instead of casting pointers, we do a proper unaligned load using
copy_nonoverlapping.
Benchmarks appear unaffected on Linux x64.
=> Fixes undefined behavior reported in #47.

src/lib.rs
This allows byteorder to be used in a no_std context.
=> Replacing std size_of with core size_of.

src/lib.rs
This adds trait bounds to ByteOrder for all the traits that can
automatically be derived. Next, it derives them all for BigEndian and
LittleEndian. The exception is Default, which cannot be derived for
enums, and it is explicitly implemented as unreachable.
Fixes #52.
r? @BurntSushi
=> Require impls for all derive-able traits for ByteOrder

Cargo.toml, src/lib.rs, src/new.rs
For the html_root_url I used the exact docs.rs version and just put an obnoxious comment in the toml file to remind authors to update the two together. Other suggestions very welcome.
I did not specify either html_logo_url or html_favicon_url like many official Rust crates do since we didn't talk about it, but it seems like we need guidelines on those too.
=> Simple fixes for #76

src/lib.rs
I'm not sure if it makes more sense documentation-wise to hide the various derived traits inside the sealed trait, or show them publically, but still seal the `ByteOrder` trait. I just did it as described in the issue for now; happy to change it of course.
Fixes #69
Updates #76
=> Seal ByteOrder trait against external implementations

src/lib.rs, src/new.rs
I think there might be a handful of extra things that I missed, but this copies the basic examples from the trait docs into the actual methods (updating for bit width / signedness, of course). Most examples use little endian ordering except the ones on the `BigEndian` type itself.
Examples are identical for same sign/width read/write methods so there's some duplication that's not strictly necessary, but it will look nice in the docs and means you don't have to go hunting for an example.
Updates #75
Updates #76
=> Add examples to most methods

src/lib.rs, src/new.rs
The trait has default implementations around read_int/read_uint to keep all existing instances working without changes, but implementations can implement something more optimal if needed.
This seems useful to have as 24 bit integers are quite common in various data formats, and having convenience functions for this prevents a few keystrokes every time.
=> Add 24 bit integer read/write functions

src/lib.rs
Unsigned integer types were given for the signed functions of the ByteOrder trait
=> Fix some typos in the docs

src/lib.rs
Part two:
Fixes some typos in the examples I pushed yesterday, and also hits all the {u,i}128 methods. Sorry for the confusion on the last PR.
*EDIT:* These do work locally, but Travis doesn't seem to be running them. Should we also add a `--features "i128"` to the .travis file?
=> Add more examples for {u,i}128 methods

Cargo.toml
The `repository` key only takes the username and repository name, not a full URL (the default `service` is GitHub). See http://doc.crates.io/manifest.html
The `branch` key defaults to `master` so I removed it for simplicity.
=> Cleanup CI badge

README.md
PNG looks pixelated on Apple's retina screens.
=> Use SVG for Travis badge

src/lib.rs
The similar `big_endian` tests were using an offset to read from the
end of the written `u64`, but the `native_endian` tests were reading
directly, just like the `little_endian` tests.  That's of course only
correct when the target actually is little endian.
That `big_endian` offset is now sliced directly, instead of cloning into
another vector, and then this logic is also used in the `native_endian`
test, depending on the current `#[cfg(target_endian)]`.
Fixes #102.
=> Fix prop_ext_[u]int_*::native_endian on BE targets

src/lib.rs
This is the mirror commit to https://github.com/rust-lang/rust/pull/46012
=> make int->float conversion a transmute

src/io.rs
Since nearly 2 years, there is a depcrated attribute, which can be used 
https://github.com/rust-lang/rfcs/blob/master/text/1270-deprecation.md
=> Use depcrated tag instead of pure documentation

.travis.yml, Cargo.toml, ci/script.sh
This rolls up #110, #113 and #114. It also does a reorg of CI. I'd like to keep updating dev dependencies, but `rand 0.4` requires a version of Rust newer than `1.12`. So we change CI to only make sure that `byteorder` builds on `1.12`, but don't run tests.
=> rollup + fix CI

benches/bench.rs, src/lib.rs
I kept the crate feature for now so we don't need to increase the minimum rust version. I'd appreciate publishing a new version with this so I can use it with stable rust.
=> Get rid of i128 rust feature (now stable)

src/io.rs, src/lib.rs
I ran into 48-bit integers in SQLite's file format, so these methods would be nice to have.
Please peruse my changes.  I did my best to triple check everything, but they were copy-pasted from the 24-bit methods and it's easy to accidentally miss something when copy pasting code.
By the way, I didn't see any tests that exercise the WriteBytesExt methods.
=> Add {u,i}48 methods

CHANGELOG.md, Cargo.toml, benches/bench.rs, build.rs, src/io.rs, src/lib.rs
This PR fixes a few small bugs, deprecates `read_{f32,f64}_into_unchecked` (in favor of `read_{f32,f64}_into`) and automatically enables `i128` support for Rust compilers that have it.
ref https://github.com/TyOverby/bincode/issues/250
=> prep for 1.3 release

src/io.rs
These methods are analogous to the already-existing `read_u8` and `read_i8` methods on `ReadBytesExt`. The `read_u8_into` method is primarily useful just for completeness, since it's equivalent to `read_exact`, but the `read_i8_into` method is useful for client code that wants to avoid `unsafe`.
=> Add read_i8_into to ReadBytesExt

src/lib.rs
Building on #147, this improves the ergonomics of i8 slice methods in two ways:
1. Changes `ReadBytesExt::read_i8_into` to use a more strict unsafe cast. While this does not change safety or optimized build performance at opt-level 2, it does marginally improve debug code size ([godbolt diff](https://godbolt.org/z/QQKDhg)).
2. Adds a `ByteOrder::write_i8_into` method for completeness and parity with other types, which prevents users having to write their own unsafe blocks or loops with `write_i8` for what is just a slice copy. This parity with other types is especially convenient when macro-generating code per-type since one can treat i8 like all other types ([example](https://github.com/aschampion/rust-n5/blob/d3b3479963d08aef769f3fa52f0c3958c5ab010b/src/lib.rs#L321-L384)).
=> Improve i8 slice methods

.github/workflows/ci.yml, Cargo.toml, README.md, src/lib.rs
Setting the pinned version to 1.28.0 was an oversight. It was most
likely the result of a copy & paste error in #159.
We also remove doc_comment, since its MSRV is quite high.
Thanks to @ZoeyR for [pointing this out](https://github.com/BurntSushi/byteorder/pull/159#issuecomment-604224759).
=> ci: change MSRV back to 1.12.0 in CI

src/lib.rs
Before, the example in the docs for `ByteOrder::from_slice_i32` caused Miri to error with the message, "error: Undefined Behavior: trying to reborrow for Unique at alloc1389, but parent tag <untagged> does not have an appropriate item in the borrow stack". Now it runs without errors (tested locally by creating an example and running it with `cargo +nightly miri run --example the_example`).
([This is the example in the Rust Playground.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d241757cc72e45a5d5e08a7084bb3065) You can run it with Miri by selecting "Miri" from the "Tools" menu.)
Fwiw, I'm not sure if the original code really has undefined behavior or not, but this PR is a simple change, and the new code is a little clearer anyway.
=> Change as_ptr to as_mut_ptr to fix Miri error

.github/workflows/ci.yml, Cargo.toml, README.md, benches/bench.rs, src/lib.rs
=> rollup: fixup CI and endianness conversion improvements

src/lib.rs
`pack_size()` and `pack_size128()` can be written in more compact form, taking advantage of CPU capabilities of counting leading zeros in a number. I've quickly checked that `pack_size()` on Aarch64 it shrinks down from 27 to 5 opcodes, and on X86_64: from 26 to 8.
=> Simplify pack_size() and pack_size128()

src/lib.rs
This eliminates four unsafe blocks by using methods from the standard library.
=> Use safe code for floating point endian conversion
